### ISSUE TITLE
Fix browser support

### ISSUE THREAD

**Issue by jetexe** [json-schema-tools/dereferencer#60]
`fs.constants` is undefined from browser  

https://github.com/json-schema-tools/dereferencer/blob/86775c8fc4827a3ee28b123622d5c1ca4246747d/src/dereferencer.ts#L158

https://github.com/json-schema-tools/dereferencer/blob/86775c8fc4827a3ee28b123622d5c1ca4246747d/src/index-web.ts#L4-L7

**Comment by BelfordZ** [comment]
thanks for the issue. Ill get this resolved asap.
